# Generated by Django 3.2.18 on 2023-04-15 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdressTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdressType', models.CharField(max_length=30, verbose_name='نوع آدرس')),
            ],
            options={
                'verbose_name': 'جدول پایه نوع آدرس',
                'verbose_name_plural': 'جدول پایه نوع آدرس',
            },
        ),
        migrations.CreateModel(
            name='BaseChaildeTaghismbandiKoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Childe', models.CharField(max_length=20, verbose_name='تقسیم بندی جزعی')),
            ],
            options={
                'verbose_name': 'جدول پایه حوزه فعالیت جزعی',
                'verbose_name_plural': 'جدول پایه حوزه فعالیت جزعی',
            },
        ),
        migrations.CreateModel(
            name='BaseEmailTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailTypeModel', models.CharField(max_length=30, verbose_name='نوع ایمیل')),
            ],
            options={
                'verbose_name': 'جدول پایه نوع ایمیل',
                'verbose_name_plural': 'جدول پایه نوع ایمیل',
            },
        ),
        migrations.CreateModel(
            name='BaseHozeieAsliFaliatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='سمت')),
            ],
            options={
                'verbose_name': 'جدول پایه نوع اصلی فعالیت',
                'verbose_name_plural': 'جدول پایه نوع اصلی فعالیت',
            },
        ),
        migrations.CreateModel(
            name='BaseMessangerTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialMedia', models.CharField(max_length=30, verbose_name='نوع پیامرسان')),
            ],
            options={
                'verbose_name': 'جدول پایه نام مسنجر ها',
                'verbose_name_plural': 'جدول پایه نام مسنجر ها',
            },
        ),
        migrations.CreateModel(
            name='BaseSemat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='سمت')),
            ],
            options={
                'verbose_name': 'جدول پایه سمت شخص',
                'verbose_name_plural': 'جدول پایه سمت شخص',
            },
        ),
        migrations.CreateModel(
            name='BaseSocialMediaTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialMedia', models.CharField(max_length=30, verbose_name='نام مولتی مدیا')),
            ],
            options={
                'verbose_name': 'جدول پایه نام مولتی مدیا',
                'verbose_name_plural': 'جدول پایه نام مولتی مدیا',
            },
        ),
        migrations.CreateModel(
            name='BaseStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=30, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'جدول پایه نام استان',
                'verbose_name_plural': 'جدول پایه نام استان',
            },
        ),
        migrations.CreateModel(
            name='BaseTaghismbandiKoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=20, verbose_name='گروه حوزه فعالیت مادر')),
            ],
            options={
                'verbose_name': 'جدول پایه حوزه فعالیت مادر',
                'verbose_name_plural': 'جدول پایه حوزه فعالیت مادر',
            },
        ),
        migrations.CreateModel(
            name='BaseTellTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TellType', models.CharField(max_length=30, verbose_name='نوع تلفن')),
            ],
            options={
                'verbose_name': 'جدول پایه نوع تلفن',
                'verbose_name_plural': 'جدول پایه نوع تلفن',
            },
        ),
        migrations.CreateModel(
            name='BaseWebsiteTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebsiteType', models.CharField(max_length=30, verbose_name='نوع وبسایت')),
            ],
            options={
                'verbose_name': 'جدول پایه نوع وب سایت',
                'verbose_name_plural': 'جدول پایه نوع وب سایت',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('Shenaseh', models.CharField(blank=True, max_length=30, null=True, verbose_name='شناسه')),
                ('ShenasehMeli', models.CharField(blank=True, max_length=30, null=True, verbose_name='شناسه ملی')),
                ('ShomarehSabt', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره ثبت')),
                ('KodeEghtesadi', models.CharField(blank=True, max_length=30, null=True, verbose_name='کد اقتصادی')),
                ('CreateDate', models.TimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True, verbose_name='وضعیت مخاطب')),
                ('Order', models.IntegerField(default=10, help_text='Lower number are going closer to the top in result set', verbose_name='ترتیب مرتب سازی')),
                ('HozeieAsliFaliat', models.ManyToManyField(to='Contacts.BaseHozeieAsliFaliatModel', verbose_name='حوزه اصلی فعالیت')),
                ('HozeieFaliat', models.ManyToManyField(to='Contacts.BaseChaildeTaghismbandiKoli', verbose_name='حوزه فعالیت')),
            ],
            options={
                'verbose_name': 'کمپانی',
                'verbose_name_plural': 'کمپانی',
            },
        ),
        migrations.CreateModel(
            name='Preson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100, verbose_name='')),
                ('Departeman', models.CharField(blank=True, max_length=21, null=True, verbose_name='دپارتمان')),
                ('CodeMeli', models.CharField(blank=True, max_length=14, null=True, verbose_name='کد ملی')),
                ('MahdodehieKari', models.CharField(blank=True, max_length=21, null=True, verbose_name='محدوده کاری')),
                ('sex', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن'), (3, 'نامشخص')], default=3, verbose_name='جنسیت')),
                ('CreateDate', models.TimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('Order', models.IntegerField(default=0, help_text='Lower number are going closer to the top in result set', null=True, verbose_name='ردیف مرتب سازی')),
                ('CompanyRelation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contacts.company', verbose_name='مرتبط با کمپانی')),
                ('HozeieAsliFaliat', models.ManyToManyField(to='Contacts.BaseHozeieAsliFaliatModel', verbose_name='حوزه اصلی فعالیت')),
                ('HozeieFaliat', models.ManyToManyField(to='Contacts.BaseChaildeTaghismbandiKoli', verbose_name='حوزه فعالیت')),
                ('Semat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basesemat', verbose_name='سمت کاری')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'شخص',
            },
        ),
        migrations.CreateModel(
            name='Tozihat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KindOgActivity', models.CharField(max_length=20, verbose_name='توضیحات تکمیلی')),
            ],
            options={
                'verbose_name': 'جدول پایه توضیحات تکمیلی',
                'verbose_name_plural': 'جدول پایه توضیحات تکمیلی',
            },
        ),
        migrations.CreateModel(
            name='WbSitePreson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TellNumber', models.CharField(max_length=20, verbose_name='آدرس وبسایت')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basewebsitetypemodel', verbose_name='نوع وبسایت')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.preson', verbose_name='مرتبط با شخص')),
            ],
            options={
                'verbose_name': 'سایت شخص',
                'verbose_name_plural': 'سایت شخص',
            },
        ),
        migrations.CreateModel(
            name='WbSiteCompony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TellNumber', models.CharField(max_length=200, verbose_name='آدرس سایت')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basewebsitetypemodel', verbose_name='نوع وبسایت')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.company', verbose_name='مرتبط با کمپانی')),
            ],
            options={
                'verbose_name': 'وب سایت کمپانی',
                'verbose_name_plural': 'وب سایت کمپانی',
            },
        ),
        migrations.CreateModel(
            name='TellPreson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TellNumber', models.CharField(max_length=100, verbose_name='شماره')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basetelltypemodel', verbose_name='نوع تلفن')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.preson', verbose_name='مرتبط با شخص')),
            ],
            options={
                'verbose_name': 'تلفن تماس شخص',
                'verbose_name_plural': 'تلفن تماس شخص',
            },
        ),
        migrations.CreateModel(
            name='TellComony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TellNumber', models.CharField(max_length=100, verbose_name='تلفن')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basetelltypemodel', verbose_name='نوع تلفن')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.company', verbose_name='مرتبط با کمپانی')),
            ],
            options={
                'verbose_name': 'تلفن کمپانی',
                'verbose_name_plural': 'تلفن کمپانی',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworksPreson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDNumber', models.CharField(max_length=100, verbose_name='آیدی')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basesocialmediatypemodel', verbose_name='نوع مولتی مدیا')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.preson', verbose_name='مرتبط با شخص')),
            ],
            options={
                'verbose_name': 'مولتی مدیا شخص',
                'verbose_name_plural': 'مولتی مدیا شخص',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworksCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDNumbers', models.CharField(max_length=100, verbose_name='لینک')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basesocialmediatypemodel', verbose_name='نوع سوشیال مدیا')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.company', verbose_name='مرتبط با کمپانی')),
            ],
            options={
                'verbose_name': 'مولتی مدیا کمپانی',
                'verbose_name_plural': 'مولتی مدیا کمپانی',
            },
        ),
        migrations.AddField(
            model_name='preson',
            name='TozihateKar',
            field=models.ManyToManyField(to='Contacts.Tozihat', verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='preson',
            name='UserCreate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MessangerPreson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numbers', models.CharField(max_length=100, verbose_name='شماره')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basemessangertypemodel', verbose_name='نوع مسنجر')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.preson', verbose_name='مرتبط با شخص')),
            ],
            options={
                'verbose_name': 'پیغامگیر شخص',
                'verbose_name_plural': 'پیغامگیر شخص',
            },
        ),
        migrations.CreateModel(
            name='MessangerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numbers', models.CharField(max_length=100, verbose_name='شماره')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basemessangertypemodel', verbose_name='پیام رسان')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.company', verbose_name='مرتبط با کمپانی')),
            ],
            options={
                'verbose_name': 'پیغامگیر های کمپانی',
                'verbose_name_plural': 'پیغامگیر های کمپانی',
            },
        ),
        migrations.CreateModel(
            name='EmailPreson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TellNumber', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.baseemailtypemodel', verbose_name='نوع ایمیل')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.preson', verbose_name='مرتبط با شخص')),
            ],
            options={
                'verbose_name': 'ایمیل شخص',
                'verbose_name_plural': 'ایمیل شخص',
            },
        ),
        migrations.CreateModel(
            name='EmailCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TellNumber', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.baseemailtypemodel', verbose_name='نوع ایمیل')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.company', verbose_name='مرتبط با کمپانی')),
            ],
            options={
                'verbose_name': 'ایمیل کمپانی',
                'verbose_name_plural': 'ایمیل کمپانی',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='TozihateKar',
            field=models.ManyToManyField(to='Contacts.Tozihat', verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='company',
            name='UserCreate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='basechaildetaghismbandikoli',
            name='Father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contacts.basetaghismbandikoli', verbose_name='تقسیم بندی کلی'),
        ),
        migrations.CreateModel(
            name='AddressPreson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='خیابان')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='شهر')),
                ('zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('OtherText', models.TextField(blank=True, null=True, verbose_name='ادامه آدرس')),
                ('State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contacts.basestatemodel', verbose_name='استان')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Contacts.preson', verbose_name='مرتبط با شخص')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Contacts.baseadresstypemodel', verbose_name='نوع آدرس')),
            ],
            options={
                'verbose_name': 'آدرس شخص',
                'verbose_name_plural': 'آدرس شخص',
            },
        ),
        migrations.CreateModel(
            name='AddressCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='خیابان')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='شهر')),
                ('zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('OtherText', models.TextField(blank=True, null=True, verbose_name='ادامه آدرس')),
                ('State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contacts.basestatemodel', verbose_name='استان')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Contacts.company', verbose_name='مرتبط با کمپانی')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Contacts.baseadresstypemodel', verbose_name='نوع آدرس')),
            ],
            options={
                'verbose_name': 'آدرس کمپانی',
                'verbose_name_plural': 'آدرس کمپانی',
            },
        ),
    ]
